### ISSUE TITLE
Libcwav.3dsx execution on Citra result

### ISSUE THREAD

**Issue by LindiFlaine** [mariohackandglitch/libcwav#1]
I opened Citra on my Windows 10 and then run Libcwav.3ds, and when playing each BCWAV file it's all mute.

**Comment by LindiFlaine** [comment]
Accidental

**Comment by PabloMK7** [comment]
Hello! Keep in mind the following facts when testing this on citra:
1) The csnd service is not implemented at all on citra, you need to use a real 3ds to test it out.
2) The dsp service requires the presence of `3ds/dspfirm.cdc` in the emulated SD folder (you can just create an empty file in that location with that name).

**Comment by PabloMK7** [comment]
Closed because OP doesn't respond, so I guess it was user error.
